services:
  test-blue:
    image: eatda:test-blue
    container_name: eatda-test-blue
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /home/ubuntu/eatda/test:/root/eatda
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  test-green:
    image: eatda:test-green
    container_name: eatda-test-green
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /home/ubuntu/eatda/test:/root/eatda
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

networks:
  backend:
    external: true
    name: backend
