services:
  ai:
    image: eatda-ai:latest
    container_name: eatda-ai
    ports:
      - "8085:8000"
    volumes:
      - /home/ubuntu/eatda/ai:/home/ubuntu/eatda/ai
    networks:
      - backend
    command: >
      gunicorn -k uvicorn.workers.UvicornWorker main:app -w 4 -b 0.0.0.0:8000

networks:
  backend:
    external: true
    name: backend
