spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eatda?serverTimezone=Asia/Seoul
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.domain..controller: DEBUG
    com.domain..service: DEBUG
    com.domain..repository: TRACE
    org.hibernate.SQL: DEBUG                 # Hibernate SQL 로그
    org.hibernate.type.descriptor.sql: TRACE # SQL 파라미터 값까지

  이건 application-local.yml,
spring:
  datasource:
    url: jdbc:mysql://prod-host:3306/prod_db
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.domain..controller: INFO
    com.domain..service: WARN
    com.domain..repository: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF

filestorage: # 파일 저장소 설정
  public-base-url: https://i13a609.p.ssafy.io

springdoc:
  swagger-ui:
    config-url: /prod/v3/api-docs/swagger-config
    url: /prod/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
